site_name: Graph Miniaturization

theme: material

plugins:
    - search 
    - mkdocstrings:
        handlers:
            python:
                paths: [src]
                options:
                    ignore_init_summary: false
                    show_root_heading: True
                    show_root_full_path: False
                    show_symbol_type_heading: True
                    show_symbol_type_toc: True
                    show_category_heading: False
                    show_source: False
                    show_inheritance_diagram: True

                    docstring_style: numpy
                    docstring_section_style: table
                    
                    filters:
                        - "__init__"
                        - "!^__(?!init__$)"
                        
                    #show_root_toc_entry: false

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

nav:
    - Home: index.md
    - Reference:
        - Simulation:   reference/simulation.md
        - MCMC: reference/mcmc.md
    # - Tutorial
    # - How-to
    # - Explanation

