site_name: Graph Miniaturization

theme: 
    name: material
    features: 
        - navigation.tabs 
        - navigation.top 
        - navigation.sections
        - navigation.instant
        - navigation.footer
plugins:
    - search 
    - mkdocstrings:
        handlers:
            python:
                paths: [src]
                options:
                    ignore_init_summary: false
                    show_root_heading: True
                    show_root_full_path: True
                    show_symbol_type_heading: True
                    show_symbol_type_toc: True
                    show_category_heading: True
                    show_source: True
                    show_signatures: True
                    show_inheritance_diagram: True
                    show_attributes: True

                    docstring_style: numpy
                    docstring_section_style: list
                    
                    # filters:
                    #     - "__init__"
                    #     - "!^__(?!init__$)"
                        
                    #show_root_toc_entry: false

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

nav:
  - Home: index.md
  - API Reference:
      - minigraphs.simulation:  reference/simulation.md
      - minigraphs.mcmc:        reference/mcmc.md
      - minigraphs.metrics:     reference/metrics.md 
      - minigraphs.reduction:   reference/reduction.md

