site_name: Metropolis-Hastings Graph Miniaturization

theme: material

plugins:
    - search 
    - mkdocstrings:
        handlers:
            python:
                paths: [src]
                options:
                    ignore_init_summary: false
                    #show_root_heading: false
                    #show_root_toc_entry: false


nav:
    - Home: index.md
    - Reference:
        - Miniaturize: reference/miniaturize.md
        - Simulation:   reference/simulation.md
    # - Tutorial
    # - How-to
    # - Explanation

