generators:
  density:
    targets: "10 ** np.arange(-1.70,0,0.15)"
    n_samples: 1
  clustering:
    targets: "np.arange(0.05,0.95,0.05)"
    n_samples: 1
  assortativity:
    targets: "np.linspace(-0.95,0.95,19)"
    n_samples: 1

simulations:
  sir:
    tau: 0.1 
    gamma: 0.1 
    n_steps: 1000
    n_trials: 2