metrics:
  - "density"
  - "clustering"

density:
  inputs: "10 ** np.linspace(-2,1,10)"
  n_graphs: 1

clustering:
  inputs: "np.linspace(0.1,0.9,10)"
  n_graphs: 1

n_vertices: 100

sir:
  - n_steps: 1000

degroot: 
  - n_steps: 1000