graph: "giant/hamsterster"
miniatures:
  min_1:
    alpha: 0.25
    n_changes: 10
    params:
      n_trials: 30
      n_steps: 100
    pt:
      n_steps: 20000
      n_substeps: 100
    
  min_2:
    alpha: 0.50
    n_changes: 10
    params:
      n_trials: 30
      n_steps: 100
    pt:
      n_steps: 20000
      n_substeps: 100

  min_3:
    alpha: 0.75
    n_changes: 10
    params:
      n_trials: 30
      n_steps: 100
    pt:
      n_steps: 20000
      n_substeps: 100

    
      
models:
  sir:
    tau: 0.1
    gamma: 0.1
    n_steps: 500
    n_trials: 15