seed: 42

miniaturization:
    warmup:
      n_steps: 100
      n_trials: 30
    setup:
      n_miniatures: 3

    hamsterster:
      min_200:
        n_exchanges: 50
        n_steps: 50
        targets:
          - density
          - clustering
          - assortativity

    sir:
      n_steps: 500
      n_trials: 10
      tau: 0.1
      gamma: 0.1



