seed: 42

miniaturization:
    warmup:
      n_steps: 100
      n_trials: 30
    n_miniatures: 3

    hamsterster:
      targets:
        - density
        - clustering
        - assortativity_norm 

      min_600:
        n_exchanges: 400
        n_steps: 50
        
      min_400:
        n_exchanges: 400
        n_steps: 50

      min_200:
        n_exchanges: 400
        n_steps: 50

    giant_soc-pages-tvshow:
      targets:
        - density
        - clustering
        - assortativity_norm
      
      min_1170:
        n_exchanges: 600
        n_steps: 50 

      min_780:
        n_exchanges: 600
        n_steps: 50 

      min_390:
        n_exchanges: 600
        n_steps: 50 

      

    

    sir:
      n_steps: 500
      n_trials: 10
      tau: 0.2
      gamma: 0.1

    layout:
      max_iter: 500



