graph: "hamsterster"
miniatures:
  min_1:
    alpha: 0.85
    n_changes: 1
    params:
      n_trials: 10
      n_steps: 100
    pt:
      n_steps: 1000
      n_substeps: 100

  min_2:
    alpha: 0.90
    n_changes: 1
    params:
      n_trials: 10
      n_steps: 100
    pt:
      n_steps: 1000
      n_substeps: 100

  min_3:
    alpha: 0.95
    n_changes: 1
    params:
      n_trials: 10
      n_steps: 100
    pt:
      n_steps: 1000
      n_substeps: 100

viz:
  max_iter: 1000

sir:
  tau: 0.1
  gamma: 0.1
  n_steps: 500
  n_trials: 15