n_trials: 10
graphs_dir: "/mnt/home/martjor/repos/dev_pt/workflows/data/networks"
test_id: "test"
methods:
  sparsification:
    n_graphs: 10
    parameters:
      stretch: "10 ** np.linspace(1,2,20)"
  coarsening:
    n_graphs: 1
    parameters:
      alpha: "np.linspace(0.05,0.95,20)"
models:
  sir:
    tau: 0.1
    gamma: 0.1
    n_steps: 1000
    n_trials: 100