name: Build Documentation using MkDocs

on: 
  push:
    branches: [project]
  pull_request:
    branches: [project]

jobs:
  build:
    name: Build and Deploy Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v2
      
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python - pip install --upgrade pip
          pip install mkdocs-material
          pip install 'mkdocstrings[python]'
      
      - name: Deploy
        run: | 
          git pull
          mkdocs gh-deploy
